package main

import (
	"fmt"
	"go/format"
	"sort"
	"strconv"
	"strings"
)

var schemaTypeConstants = map[string]string{
	"object":  "provider.ResourceDefinitionsSchemaTypeObject",
	"array":   "provider.ResourceDefinitionsSchemaTypeArray",
	"map":     "provider.ResourceDefinitionsSchemaTypeMap",
	"union":   "provider.ResourceDefinitionsSchemaTypeUnion",
	"string":  "provider.ResourceDefinitionsSchemaTypeString",
	"integer": "provider.ResourceDefinitionsSchemaTypeInteger",
	"float":   "provider.ResourceDefinitionsSchemaTypeFloat",
	"boolean": "provider.ResourceDefinitionsSchemaTypeBoolean",
}

// Renders the per-type Go source: a resource constructor and a
// schema builder, both calling into the generic Cloud Control engine.
func emitResourceFile(res *irResource) ([]byte, error) {
	ident := goIdentifier(res.CFNType)
	var b strings.Builder

	fmt.Fprintf(&b, "func %sResource(\n", ident)
	b.WriteString("\tcloudControlServiceFactory pluginutils.ServiceFactory[*aws.Config, cloudcontrolservice.Service],\n")
	b.WriteString("\tresourceGroupTaggingServiceFactory pluginutils.ServiceFactory[*aws.Config, resgrouptagservice.Service],\n")
	b.WriteString("\tawsConfigStore pluginutils.ServiceConfigStore[*aws.Config],\n")
	b.WriteString(") provider.Resource {\n")
	b.WriteString("\treturn cloudcontrol.CCResource(\n")
	b.WriteString("\t\tcloudcontrol.CCResourceConfig{\n")
	fmt.Fprintf(&b, "\t\t\tBlueprintType:        %q,\n", res.BlueprintType)
	fmt.Fprintf(&b, "\t\t\tCFNType:              %q,\n", res.CFNType)
	fmt.Fprintf(&b, "\t\t\tLabel:                %q,\n", res.Label)
	fmt.Fprintf(&b, "\t\t\tFormattedDescription: %q,\n", res.Description)
	fmt.Fprintf(&b, "\t\t\tSchema:               overlays.Apply(%q, %sSchema()),\n", res.BlueprintType, ident)
	fmt.Fprintf(&b, "\t\t\tFormattedExamples:    readExamples(%q),\n", exampleStem(res.CFNType))
	fmt.Fprintf(&b, "\t\t\tMeta: %s,\n", metaLiteral(res))
	b.WriteString("\t\t},\n")
	b.WriteString("\t\tcloudControlServiceFactory,\n")
	b.WriteString("\t\tresourceGroupTaggingServiceFactory,\n")
	b.WriteString("\t\tawsConfigStore,\n")
	b.WriteString("\t)\n}\n\n")

	fmt.Fprintf(&b, "func %sSchema() *provider.ResourceDefinitionsSchema {\n", ident)
	b.WriteString("\treturn ")
	b.WriteString(renderSchema(res.Schema, 1))
	b.WriteString("\n}\n")

	body := b.String()
	source := fileHeader(resourceImportPaths(strings.Contains(body, "core."))) + body
	return format.Source([]byte(source))
}

// Renders just the schema builder for a data-source-only type. Its
// resource constructor and registry entry are intentionally omitted (no managed resource
// is emitted), but the generated data source still references the `<type>Schema()` builder.
func emitSchemaOnlyFile(res *irResource) ([]byte, error) {
	ident := goIdentifier(res.CFNType)
	var b strings.Builder

	fmt.Fprintf(&b, "func %sSchema() *provider.ResourceDefinitionsSchema {\n", ident)
	b.WriteString("\treturn ")
	b.WriteString(renderSchema(res.Schema, 1))
	b.WriteString("\n}\n")

	body := b.String()
	imports := []string{`"github.com/newstack-cloud/bluelink/libs/blueprint/provider"`}
	if strings.Contains(body, "core.") {
		imports = append(imports, `"github.com/newstack-cloud/bluelink/libs/blueprint/core"`)
	}
	return format.Source([]byte(fileHeader(imports) + body))
}

// Renders the cloudcontrol.CCResourceMeta literal shared by the resource
// and data source constructors (gofmt normalises the indentation).
func metaLiteral(res *irResource) string {
	var b strings.Builder
	b.WriteString("cloudcontrol.CCResourceMeta{\n")
	fmt.Fprintf(&b, "PrimaryIdentifierField: %q,\n", res.PrimaryIdentifierField)
	if len(res.PrimaryIdentifierFields) > 1 {
		fmt.Fprintf(&b, "PrimaryIdentifierFields: %s,\n", goStringSlice(res.PrimaryIdentifierFields))
	}
	fmt.Fprintf(&b, "ComputedFields: %s,\n", goStringSlice(res.ComputedFields))
	fmt.Fprintf(&b, "CreateOnlyFields: %s,\n", goStringSlice(res.CreateOnlyFields))
	fmt.Fprintf(&b, "WriteOnlyFields: %s,\n", goStringSlice(res.WriteOnlyFields))
	if res.TagPropertyName != "" {
		fmt.Fprintf(&b, "TagPropertyName: %q,\n", res.TagPropertyName)
		fmt.Fprintf(&b, "TagShape: %s,\n", res.TagShape)
	}
	if len(res.FieldNameOverrides) > 0 {
		fmt.Fprintf(&b, "FieldNameOverrides: %s,\n", goStringMap(res.FieldNameOverrides))
	}
	if len(res.JSONStringFields) > 0 {
		sorted := append([]string(nil), res.JSONStringFields...)
		sort.Strings(sorted)
		fmt.Fprintf(&b, "JSONStringFields: %s,\n", goStringSlice(sorted))
	}
	b.WriteString("}")
	return b.String()
}

func fileHeader(importPaths []string) string {
	var b strings.Builder
	b.WriteString("// Code generated by tools/awsgen. DO NOT EDIT.\n\n")
	b.WriteString("package gen\n\n")
	b.WriteString("import (\n")
	for _, path := range importPaths {
		fmt.Fprintf(&b, "\t%s\n", path)
	}
	b.WriteString(")\n\n")
	return b.String()
}

func resourceImportPaths(usesCore bool) []string {
	paths := []string{
		`"github.com/aws/aws-sdk-go-v2/aws"`,
		`"github.com/newstack-cloud/bluelink-provider-aws/services/cloudcontrol"`,
		`"github.com/newstack-cloud/bluelink-provider-aws/services/cloudcontrol/overlays"`,
		`cloudcontrolservice "github.com/newstack-cloud/bluelink-provider-aws/services/cloudcontrol/service"`,
		`resgrouptagservice "github.com/newstack-cloud/bluelink-provider-aws/services/resgrouptag/service"`,
	}
	if usesCore {
		paths = append(paths, `"github.com/newstack-cloud/bluelink/libs/blueprint/core"`)
	}
	paths = append(paths,
		`"github.com/newstack-cloud/bluelink/libs/blueprint/provider"`,
		`"github.com/newstack-cloud/bluelink/libs/plugin-framework/sdk/pluginutils"`,
	)
	return paths
}

// Renders the registry that maps each Bluelink type to its
// generated constructor.
func emitRegistryFile(resources []*irResource) ([]byte, error) {
	var b strings.Builder
	b.WriteString(fileHeader([]string{
		`"github.com/aws/aws-sdk-go-v2/aws"`,
		`cloudcontrolservice "github.com/newstack-cloud/bluelink-provider-aws/services/cloudcontrol/service"`,
		`resgrouptagservice "github.com/newstack-cloud/bluelink-provider-aws/services/resgrouptag/service"`,
		`"github.com/newstack-cloud/bluelink/libs/blueprint/provider"`,
		`"github.com/newstack-cloud/bluelink/libs/plugin-framework/sdk/pluginutils"`,
	}))

	b.WriteString("// GeneratedResources returns the Cloud Control–backed resources, keyed by\n")
	b.WriteString("// Bluelink resource type.\n")
	b.WriteString("func GeneratedResources(\n")
	b.WriteString("\tcloudControlServiceFactory pluginutils.ServiceFactory[*aws.Config, cloudcontrolservice.Service],\n")
	b.WriteString("\tresourceGroupTaggingServiceFactory pluginutils.ServiceFactory[*aws.Config, resgrouptagservice.Service],\n")
	b.WriteString("\tawsConfigStore pluginutils.ServiceConfigStore[*aws.Config],\n")
	b.WriteString(") map[string]provider.Resource {\n")
	b.WriteString("\treturn map[string]provider.Resource{\n")

	sorted := append([]*irResource(nil), resources...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].BlueprintType < sorted[j].BlueprintType })
	for _, res := range sorted {
		fmt.Fprintf(&b, "\t\t%q: %sResource(\n", res.BlueprintType, goIdentifier(res.CFNType))
		b.WriteString("\t\t\tcloudControlServiceFactory,\n")
		b.WriteString("\t\t\tresourceGroupTaggingServiceFactory,\n")
		b.WriteString("\t\t\tawsConfigStore,\n")
		b.WriteString("\t\t),\n")
	}
	b.WriteString("\t}\n}\n")

	return format.Source([]byte(b.String()))
}

func renderSchema(schema *irSchema, indent int) string {
	pad := strings.Repeat("\t", indent)
	inner := strings.Repeat("\t", indent+1)
	var b strings.Builder

	b.WriteString("&provider.ResourceDefinitionsSchema{\n")
	fmt.Fprintf(&b, "%sType: %s,\n", inner, schemaTypeConstants[schema.Type])
	if schema.Label != "" {
		fmt.Fprintf(&b, "%sLabel: %q,\n", inner, schema.Label)
	}
	if schema.Description != "" {
		fmt.Fprintf(&b, "%sDescription: %q,\n", inner, schema.Description)
	}
	renderBoolFields(&b, schema, inner)
	renderConstraints(&b, schema, inner)
	renderRequired(&b, schema, inner)
	renderAttributes(&b, schema, indent, inner)
	if schema.Items != nil {
		fmt.Fprintf(&b, "%sItems: %s,\n", inner, renderSchema(schema.Items, indent+1))
	}
	if schema.MapValues != nil {
		fmt.Fprintf(&b, "%sMapValues: %s,\n", inner, renderSchema(schema.MapValues, indent+1))
	}
	renderOneOf(&b, schema, indent, inner)
	fmt.Fprintf(&b, "%s}", pad)
	return b.String()
}

func renderBoolFields(b *strings.Builder, schema *irSchema, inner string) {
	if schema.Nullable {
		fmt.Fprintf(b, "%sNullable: true,\n", inner)
	}
	if schema.Computed {
		fmt.Fprintf(b, "%sComputed: true,\n", inner)
	}
	if schema.MustRecreate {
		fmt.Fprintf(b, "%sMustRecreate: true,\n", inner)
	}
	if schema.Sensitive {
		fmt.Fprintf(b, "%sSensitive: true,\n", inner)
	}
	if schema.IgnoreDrift {
		fmt.Fprintf(b, "%sIgnoreDrift: true,\n", inner)
	}
}

func renderConstraints(b *strings.Builder, schema *irSchema, inner string) {
	if schema.Pattern != "" {
		fmt.Fprintf(b, "%sPattern: %q,\n", inner, schema.Pattern)
	}
	if schema.MinLength != nil {
		fmt.Fprintf(b, "%sMinLength: %d,\n", inner, *schema.MinLength)
	}
	if schema.MaxLength != nil {
		fmt.Fprintf(b, "%sMaxLength: %d,\n", inner, *schema.MaxLength)
	}
	if schema.Minimum != nil {
		fmt.Fprintf(b, "%sMinimum: %s,\n", inner, renderScalar(schema.Type, *schema.Minimum))
	}
	if schema.Maximum != nil {
		fmt.Fprintf(b, "%sMaximum: %s,\n", inner, renderScalar(schema.Type, *schema.Maximum))
	}
	if len(schema.Enum) > 0 {
		fmt.Fprintf(b, "%sAllowedValues: %s,\n", inner, renderAllowedValues(schema.Enum))
	}
}

func renderRequired(b *strings.Builder, schema *irSchema, inner string) {
	if len(schema.Required) == 0 {
		return
	}
	sorted := append([]string(nil), schema.Required...)
	sort.Strings(sorted)
	fmt.Fprintf(b, "%sRequired: %s,\n", inner, goStringSlice(sorted))
}

func renderAttributes(b *strings.Builder, schema *irSchema, indent int, inner string) {
	if len(schema.Attributes) == 0 {
		return
	}
	fmt.Fprintf(b, "%sAttributes: map[string]*provider.ResourceDefinitionsSchema{\n", inner)
	attrPad := strings.Repeat("\t", indent+2)
	sorted := append([]irAttribute(nil), schema.Attributes...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Name < sorted[j].Name })
	for _, attr := range sorted {
		fmt.Fprintf(b, "%s%q: %s,\n", attrPad, attr.Name, renderSchema(attr.Schema, indent+2))
	}
	fmt.Fprintf(b, "%s},\n", inner)
}

func renderOneOf(b *strings.Builder, schema *irSchema, indent int, inner string) {
	if len(schema.OneOf) == 0 {
		return
	}
	fmt.Fprintf(b, "%sOneOf: []*provider.ResourceDefinitionsSchema{\n", inner)
	itemPad := strings.Repeat("\t", indent+2)
	for _, branch := range schema.OneOf {
		fmt.Fprintf(b, "%s%s,\n", itemPad, renderSchema(branch, indent+2))
	}
	fmt.Fprintf(b, "%s},\n", inner)
}

func renderScalar(schemaType string, value float64) string {
	if schemaType == "integer" {
		return fmt.Sprintf("core.ScalarFromInt(%d)", int(value))
	}
	return fmt.Sprintf("core.ScalarFromFloat(%s)", strconv.FormatFloat(value, 'g', -1, 64))
}

func renderAllowedValues(values []string) string {
	var b strings.Builder
	b.WriteString("[]*core.MappingNode{")
	for i, value := range values {
		if i > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(&b, "core.MappingNodeFromString(%q)", value)
	}
	b.WriteString("}")
	return b.String()
}

func goStringMap(values map[string]string) string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	var b strings.Builder
	b.WriteString("map[string]string{")
	for i, key := range keys {
		if i > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(&b, "%q: %q", key, values[key])
	}
	b.WriteString("}")
	return b.String()
}

func goStringSlice(values []string) string {
	if len(values) == 0 {
		return "nil"
	}
	var b strings.Builder
	b.WriteString("[]string{")
	for i, value := range values {
		if i > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(&b, "%q", value)
	}
	b.WriteString("}")
	return b.String()
}

// Derives a Go function-name stem from a CFN type, e.g.
// "AWS::DynamoDB::Table" -> "dynamodbTable".
func goIdentifier(cfnType string) string {
	parts := strings.Split(cfnType, "::")
	if len(parts) < 3 {
		return lowerFirst(strings.ReplaceAll(cfnType, "::", ""))
	}

	return strings.ToLower(parts[1]) + parts[2]
}
